repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        language: python
        entry: yapf
        args: ["-i", "-r"]
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
